### ISSUE TITLE
Unable to create a new PDFJpegImage

### ISSUE THREAD

**Issue by IDispose** [o2solutions/pdf4net#3]
I have a jpg file in Azure datalake. I can create a stream to retrieve the file contents. However trying to use that stream to create a new `PDFJpegImage` throws exception `Width cannot be zero`
```
Width cannot be less than or equal to zero.
Parameter name: Width

   at O2S.Components.PDF4NET.Graphics.PDFJpegImage.set_Width(Int32 value)
   at O2S.Components.PDF4NET.Graphics.PDFJpegImage.ConnectMenuItem(Stream currentSyncObject)
   at ImageToPDFConverter.DataLakePayloadManager.<ReadAsync>d__2.MoveNext() in C:\Arms\ImageToPDFConverter\DataLakePayloadManager.cs:line 33
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ImageToPDFConverter.CreatePDF.<Run>d__2.MoveNext() in C:\Arms\ImageToPDFConverter\CreatePDF.cs:line 44
```
Unfortunately, the documentation, although lists members and properties, is not very useful in developing real working code. Where can I find good working samples?

**Comment by pdf4dev-solutions-support** [comment]
The most probable cause is that the image file is not a JPEG image. The next release will include a fix in this area, a more descriptive exception will be thrown when the PDFJpegImage object is created. If the image is indeed JPEG, then please attach it here and we'll investigate the issue.
